# Generated by Django 3.0.8 on 2020-12-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_topping', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=30, null=True)),
                ('pizza_size_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_size_category', to='API.PizzaSize')),
                ('pizza_topping_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pizza_topping_category', to='API.PizzaTopping')),
            ],
        ),
    ]
